# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import game_pb2 as game__pb2


class GameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.connection = channel.unary_unary(
                '/game.Game/connection',
                request_serializer=game__pb2.User.SerializeToString,
                response_deserializer=game__pb2.Status.FromString,
                )
        self.disconnection = channel.unary_unary(
                '/game.Game/disconnection',
                request_serializer=game__pb2.User.SerializeToString,
                response_deserializer=game__pb2.Status.FromString,
                )
        self.answer_question = channel.unary_unary(
                '/game.Game/answer_question',
                request_serializer=game__pb2.AnswerRequest.SerializeToString,
                response_deserializer=game__pb2.AnswerResponse.FromString,
                )
        self.get_result_table = channel.unary_unary(
                '/game.Game/get_result_table',
                request_serializer=game__pb2.Empty.SerializeToString,
                response_deserializer=game__pb2.TotalRating.FromString,
                )
        self.get_question_stream = channel.unary_stream(
                '/game.Game/get_question_stream',
                request_serializer=game__pb2.Empty.SerializeToString,
                response_deserializer=game__pb2.Question.FromString,
                )


class GameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def connection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def disconnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def answer_question(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_result_table(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_question_stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'connection': grpc.unary_unary_rpc_method_handler(
                    servicer.connection,
                    request_deserializer=game__pb2.User.FromString,
                    response_serializer=game__pb2.Status.SerializeToString,
            ),
            'disconnection': grpc.unary_unary_rpc_method_handler(
                    servicer.disconnection,
                    request_deserializer=game__pb2.User.FromString,
                    response_serializer=game__pb2.Status.SerializeToString,
            ),
            'answer_question': grpc.unary_unary_rpc_method_handler(
                    servicer.answer_question,
                    request_deserializer=game__pb2.AnswerRequest.FromString,
                    response_serializer=game__pb2.AnswerResponse.SerializeToString,
            ),
            'get_result_table': grpc.unary_unary_rpc_method_handler(
                    servicer.get_result_table,
                    request_deserializer=game__pb2.Empty.FromString,
                    response_serializer=game__pb2.TotalRating.SerializeToString,
            ),
            'get_question_stream': grpc.unary_stream_rpc_method_handler(
                    servicer.get_question_stream,
                    request_deserializer=game__pb2.Empty.FromString,
                    response_serializer=game__pb2.Question.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'game.Game', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Game(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def connection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.Game/connection',
            game__pb2.User.SerializeToString,
            game__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def disconnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.Game/disconnection',
            game__pb2.User.SerializeToString,
            game__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def answer_question(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.Game/answer_question',
            game__pb2.AnswerRequest.SerializeToString,
            game__pb2.AnswerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_result_table(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/game.Game/get_result_table',
            game__pb2.Empty.SerializeToString,
            game__pb2.TotalRating.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_question_stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/game.Game/get_question_stream',
            game__pb2.Empty.SerializeToString,
            game__pb2.Question.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
