# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='game',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngame.proto\x12\x04game\"\x18\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06result\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty\"#\n\x0bTotalRating\x12\x14\n\x0ctotal_rating\x18\x01 \x01(\t\"c\n\x08Question\x12\x17\n\x0fnumber_question\x18\x01 \x01(\x05\x12\x15\n\rtext_question\x18\x02 \x01(\t\x12\x0f\n\x07\x61nswers\x18\x03 \x03(\t\x12\x16\n\x0e\x63orrect_answer\x18\x04 \x01(\x05\"O\n\rAnswerRequest\x12\x17\n\x0fnumber_question\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x13\n\x0buser_answer\x18\x03 \x01(\x05\"6\n\x0e\x41nswerResponse\x12\x14\n\x0c\x61nswer_score\x18\x01 \x01(\x08\x12\x0e\n\x06rating\x18\x02 \x01(\x05\x32\x81\x02\n\x04Game\x12&\n\nconnection\x12\n.game.User\x1a\x0c.game.Status\x12)\n\rdisconnection\x12\n.game.User\x1a\x0c.game.Status\x12<\n\x0f\x61nswer_question\x12\x13.game.AnswerRequest\x1a\x14.game.AnswerResponse\x12\x32\n\x10get_result_table\x12\x0b.game.Empty\x1a\x11.game.TotalRating\x12\x34\n\x13get_question_stream\x12\x0b.game.Empty\x1a\x0e.game.Question0\x01\x62\x06proto3'
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='game.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='game.User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=44,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='game.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='game.Status.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=70,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='game.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=79,
)


_TOTALRATING = _descriptor.Descriptor(
  name='TotalRating',
  full_name='game.TotalRating',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='total_rating', full_name='game.TotalRating.total_rating', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=116,
)


_QUESTION = _descriptor.Descriptor(
  name='Question',
  full_name='game.Question',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_question', full_name='game.Question.number_question', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_question', full_name='game.Question.text_question', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='answers', full_name='game.Question.answers', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='correct_answer', full_name='game.Question.correct_answer', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=217,
)


_ANSWERREQUEST = _descriptor.Descriptor(
  name='AnswerRequest',
  full_name='game.AnswerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_question', full_name='game.AnswerRequest.number_question', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='game.AnswerRequest.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_answer', full_name='game.AnswerRequest.user_answer', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=298,
)


_ANSWERRESPONSE = _descriptor.Descriptor(
  name='AnswerResponse',
  full_name='game.AnswerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer_score', full_name='game.AnswerResponse.answer_score', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rating', full_name='game.AnswerResponse.rating', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=354,
)

DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['TotalRating'] = _TOTALRATING
DESCRIPTOR.message_types_by_name['Question'] = _QUESTION
DESCRIPTOR.message_types_by_name['AnswerRequest'] = _ANSWERREQUEST
DESCRIPTOR.message_types_by_name['AnswerResponse'] = _ANSWERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.User)
  })
_sym_db.RegisterMessage(User)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.Status)
  })
_sym_db.RegisterMessage(Status)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.Empty)
  })
_sym_db.RegisterMessage(Empty)

TotalRating = _reflection.GeneratedProtocolMessageType('TotalRating', (_message.Message,), {
  'DESCRIPTOR' : _TOTALRATING,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.TotalRating)
  })
_sym_db.RegisterMessage(TotalRating)

Question = _reflection.GeneratedProtocolMessageType('Question', (_message.Message,), {
  'DESCRIPTOR' : _QUESTION,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.Question)
  })
_sym_db.RegisterMessage(Question)

AnswerRequest = _reflection.GeneratedProtocolMessageType('AnswerRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANSWERREQUEST,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.AnswerRequest)
  })
_sym_db.RegisterMessage(AnswerRequest)

AnswerResponse = _reflection.GeneratedProtocolMessageType('AnswerResponse', (_message.Message,), {
  'DESCRIPTOR' : _ANSWERRESPONSE,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.AnswerResponse)
  })
_sym_db.RegisterMessage(AnswerResponse)



_GAME = _descriptor.ServiceDescriptor(
  name='Game',
  full_name='game.Game',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=357,
  serialized_end=614,
  methods=[
  _descriptor.MethodDescriptor(
    name='connection',
    full_name='game.Game.connection',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='disconnection',
    full_name='game.Game.disconnection',
    index=1,
    containing_service=None,
    input_type=_USER,
    output_type=_STATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='answer_question',
    full_name='game.Game.answer_question',
    index=2,
    containing_service=None,
    input_type=_ANSWERREQUEST,
    output_type=_ANSWERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_result_table',
    full_name='game.Game.get_result_table',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_TOTALRATING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_question_stream',
    full_name='game.Game.get_question_stream',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_QUESTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAME)

DESCRIPTOR.services_by_name['Game'] = _GAME

# @@protoc_insertion_point(module_scope)
