# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cleverest_pb2 as cleverest__pb2


class CleverestStub(object):
    """игра - это чат в который нужно присоединиться и начнется игра

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connection = channel.unary_unary(
                '/cleverest.Cleverest/Connection',
                request_serializer=cleverest__pb2.ConnectionRequest.SerializeToString,
                response_deserializer=cleverest__pb2.ConnectionResponse.FromString,
                )
        self.AskQuestion = channel.unary_unary(
                '/cleverest.Cleverest/AskQuestion',
                request_serializer=cleverest__pb2.QuestionResponse.SerializeToString,
                response_deserializer=cleverest__pb2.SendUserAnswers.FromString,
                )
        self.CheckUserAnswer = channel.unary_unary(
                '/cleverest.Cleverest/CheckUserAnswer',
                request_serializer=cleverest__pb2.SendUserAnswers.SerializeToString,
                response_deserializer=cleverest__pb2.UserResults.FromString,
                )
        self.CheckUserRanking = channel.unary_unary(
                '/cleverest.Cleverest/CheckUserRanking',
                request_serializer=cleverest__pb2.LoadUserRanking.SerializeToString,
                response_deserializer=cleverest__pb2.ReturnUserRanking.FromString,
                )
        self.get_game_stream = channel.unary_stream(
                '/cleverest.Cleverest/get_game_stream',
                request_serializer=cleverest__pb2.Empty.SerializeToString,
                response_deserializer=cleverest__pb2.Action.FromString,
                )


class CleverestServicer(object):
    """игра - это чат в который нужно присоединиться и начнется игра

    """

    def Connection(self, request, context):
        """Connect to game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskQuestion(self, request, context):
        """user get question with answer => return answer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserAnswer(self, request, context):
        """check answer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserRanking(self, request, context):
        """load user rank
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_game_stream(self, request, context):
        """game stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CleverestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connection': grpc.unary_unary_rpc_method_handler(
                    servicer.Connection,
                    request_deserializer=cleverest__pb2.ConnectionRequest.FromString,
                    response_serializer=cleverest__pb2.ConnectionResponse.SerializeToString,
            ),
            'AskQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AskQuestion,
                    request_deserializer=cleverest__pb2.QuestionResponse.FromString,
                    response_serializer=cleverest__pb2.SendUserAnswers.SerializeToString,
            ),
            'CheckUserAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserAnswer,
                    request_deserializer=cleverest__pb2.SendUserAnswers.FromString,
                    response_serializer=cleverest__pb2.UserResults.SerializeToString,
            ),
            'CheckUserRanking': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserRanking,
                    request_deserializer=cleverest__pb2.LoadUserRanking.FromString,
                    response_serializer=cleverest__pb2.ReturnUserRanking.SerializeToString,
            ),
            'get_game_stream': grpc.unary_stream_rpc_method_handler(
                    servicer.get_game_stream,
                    request_deserializer=cleverest__pb2.Empty.FromString,
                    response_serializer=cleverest__pb2.Action.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cleverest.Cleverest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Cleverest(object):
    """игра - это чат в который нужно присоединиться и начнется игра

    """

    @staticmethod
    def Connection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cleverest.Cleverest/Connection',
            cleverest__pb2.ConnectionRequest.SerializeToString,
            cleverest__pb2.ConnectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AskQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cleverest.Cleverest/AskQuestion',
            cleverest__pb2.QuestionResponse.SerializeToString,
            cleverest__pb2.SendUserAnswers.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckUserAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cleverest.Cleverest/CheckUserAnswer',
            cleverest__pb2.SendUserAnswers.SerializeToString,
            cleverest__pb2.UserResults.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckUserRanking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cleverest.Cleverest/CheckUserRanking',
            cleverest__pb2.LoadUserRanking.SerializeToString,
            cleverest__pb2.ReturnUserRanking.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_game_stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/cleverest.Cleverest/get_game_stream',
            cleverest__pb2.Empty.SerializeToString,
            cleverest__pb2.Action.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
